# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shah
email: Ahmed.shahria.2017@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A gallery in progress
baseurl: "" # the subpath of your site, e.g. /blog
url: "//shahriaahmed.github.io" # the base hostname & protocol for your site
instagram_username: shvh.vx
github_username:  ShahriaAhmed

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
